version: '3'

networks:
  default:
    external:
      name: nginx-proxy

services:
  nginx:
    image: nginx
    ports:
      - "80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=www.irabu.co.tz, irabu.co.tz
      - LETSENCRYPT_HOST=www.irabu.co.tz, irabu.co.tz
      - LETSENCRYPT_EMAIL=info@irabu.co.tz
    links:
      - php
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - db
      - redis
    depends_on:
      - db

  db:
    image: mariadb
    hostname: db
    environment:
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
    volumes:
      - data-volume:/var/lib/mysql
    restart: always

  redis:
    image: redis
    hostname: redis

volumes:
  data-volume:
    driver: local
