version: '3'

networks:
  default:
    external:
      name: nginx-proxy

services:
    nginx:
      build: ./nginx
      ports:
        - "80"
      volumes:
        - ./:/var/www:cached
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      environment:
        VIRTUAL_HOST: www.irabu.co.tz, irabu.co.tz
        LETSENCRYPT_HOST: www.irabu.co.tz, irabu.co.tz
        LETSENCRYPT_EMAIL: info@irabu.co.tz
      networks:
        - default
